worker_processes auto;

events {
    worker_connections << nginx_worker_connections >>;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    sendfile    on;
    tcp_nopush  on;
    tcp_nodelay on;

    keepalive_timeout << nginx_keepalive_timeout >>;

    include /etc/nginx/conf.d/*.conf;
}
