# GENERATED by orchestrate.py — do not edit manually.
# Re-generate: python orchestrate.py generate

.PHONY: help generate build up down restart logs ps clean migrate test shell

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

generate: ## Generate all project files from orchestrate.py
	python orchestrate.py generate

build: ## Generate files and build all Docker images
	python orchestrate.py build

up: ## Generate files, build, and start all services
	python orchestrate.py up

down: ## Stop and remove all containers
	python orchestrate.py down

restart: ## Restart all services
	python orchestrate.py restart

logs: ## Follow logs from all services
	python orchestrate.py logs

ps: ## Show status of all services
	python orchestrate.py status

clean: ## Stop services and remove ALL data volumes
	python orchestrate.py clean

migrate: ## Run database migrations
	docker compose exec api alembic upgrade head

test: ## Run tests inside the API container
	docker compose exec api pytest

shell: ## Open a shell in the API container
	docker compose exec api /bin/sh
