# GENERATED by orchestrate.py from templates/migrations/env.py
# To modify application code: edit templates/migrations/env.py
# To modify config values: edit CONFIG in orchestrate.py
# Then run: python3 orchestrate.py generate
# templates/migrations/env.py — Alembic runtime migration environment
# Config values use orchestrate.py markers and are filled in at generate time.
# To modify: edit THIS file directly, then run: python3 orchestrate.py generate
#
# Docs: https://alembic.sqlalchemy.org/en/latest/autogenerate.html

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Add the api/ directory to sys.path so we can import the app module
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "api"))

from app import Base  # noqa: E402 — import after path manipulation

# Alembic Config object
config = context.config

# Set up loggers from alembic.ini
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# This is what Alembic uses to detect model changes for --autogenerate
target_metadata = Base.metadata

# Override sqlalchemy.url from environment if available
# (The alembic.ini default is: postgresql+asyncpg://taskapp:changeme_use_a_strong_password@postgres:5432/taskdb)
url_override = os.getenv("DATABASE_URL")
if url_override:
    config.set_main_option("sqlalchemy.url", url_override)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — generates SQL without connecting."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode — connects to the database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
