#!/bin/bash
# GENERATED by orchestrate.py — do not edit manually.
# Re-generate: python orchestrate.py generate
#
# Health check script for Docker HEALTHCHECK directive.
# Exit code 0 = healthy, exit code 1 = unhealthy.
# Docs: https://docs.docker.com/reference/dockerfile/#healthcheck

curl -f http://localhost:8000/ || exit 1
